name: "CI"

on: 
  push: 
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

defaults:
  run:
    working-directory: subscription_management

jobs:
  flutter_test: 
    name: Run flutter analysis and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable
          cache: true
      - name: Generate .env
        run: cp .env.example .env
      - name: Flutter pub get
        run: flutter pub get
      - name: Run flutter analysis
        run: flutter analyze
      - name: Run flutter format
        run: dart format --output=none --set-exit-if-changed lib/
      - name: Run flutter test formatter
        run: dart format --output=none --set-exit-if-changed test/
      - name: Run flutter tests
        run: flutter test --coverage
      - name: Verify coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: subscription_management/coverage/lcov.info
          min_coverage: 0
